// eslint.config.ts
// INFRA-02: ESLint v10 flat config. @adonisjs/eslint-config v3 includes:
// - @typescript-eslint strict rules
// - Import ordering rules
// - AdonisJS-specific patterns (no @ioc: strings, etc.)
import { configApp } from '@adonisjs/eslint-config'

export default [
  ...configApp(),
  {
    ignores: [
      'build/**',
      'node_modules/**',
      'database/schema.ts', // auto-generated by Lucid v22 — never edit manually
    ],
  },
]
