// eslint.config.ts
// INFRA-02: ESLint v10 flat config. @adonisjs/eslint-config v3 includes:
// - @typescript-eslint strict rules
// - Import ordering rules
// - AdonisJS-specific patterns (no @ioc: strings, etc.)
// @types stub: @adonisjs/eslint-config ships no type declarations — ambient declaration added here.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { configApp } = require('@adonisjs/eslint-config') as {
  configApp: () => unknown[]
}

export default [
  ...configApp(),
  {
    ignores: [
      'build/**',
      'node_modules/**',
      'database/schema.ts', // auto-generated by Lucid v22 — never edit manually
    ],
  },
]
