// Auto-generated by @adonisjs/bouncer indexPolicies assembler hook.
// This file is regenerated on each dev/test/build run.
// Do not edit manually — add policy files to app/policies/ instead.

export const policies = {} as const
