// database/migrations/001_foundation_tenants.ts
// INFRA-05b: UUID v7 PK for tenants. D-09.
// INFRA-04/05: Establishes the RLS grant pattern for future tables.
// Runs as 'migrator' role (DDL owner).
import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    // Tenants table — the top-level tenant registry.
    // UUID v7 PK: generated by application layer using uuidv7 npm package.
    // NOT tenant-scoped itself — no RLS needed here.
    this.schema.createTable('tenants', (table) => {
      table.uuid('id').primary().comment('UUID v7 — generated application-side via uuidv7 package')
      table.string('name', 255).notNullable()
      table.string('slug', 100).notNullable().unique()
      table.boolean('active').notNullable().defaultTo(true)
      table.timestamps(true, true)
    })

    // Grant app role access to tenants (read-only: app never inserts tenants).
    // MUST use this.schema.raw() (deferred) — NOT this.db.rawQuery() (immediate).
    // this.schema.createTable() is deferred; using rawQuery here would GRANT before CREATE TABLE runs.
    this.schema.raw(`GRANT SELECT ON tenants TO app`)

    // ──────────────────────────────────────────────────────────────────────
    // CANONICAL RLS PATTERN FOR ALL FUTURE TENANT-SCOPED TABLES
    // Copy this block into every migration that creates a tenant-scoped table.
    // Replace 'some_table' with the actual table name.
    //
    // await this.db.rawQuery(`
    //   -- 1. Enable RLS
    //   ALTER TABLE some_table ENABLE ROW LEVEL SECURITY;
    //
    //   -- 2. FORCE RLS applies RLS even to the table owner (migrator role)
    //   --    This prevents accidental bypass via direct DB connections. INFRA-05.
    //   ALTER TABLE some_table FORCE ROW LEVEL SECURITY;
    //
    //   -- 3. Create tenant isolation policy
    //   --    current_setting('app.tenant_id', true) — the 'true' arg returns NULL
    //   --    instead of error when setting is not set (safe outside transactions)
    //   CREATE POLICY tenant_isolation ON some_table
    //     USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
    //     WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);
    //
    //   -- 4. Grant DML to app role (SELECT, INSERT, UPDATE, DELETE — no DDL)
    //   GRANT SELECT, INSERT, UPDATE, DELETE ON some_table TO app;
    //   GRANT USAGE, SELECT ON some_table_id_seq TO app;
    // `)
    // ──────────────────────────────────────────────────────────────────────
  }

  async down() {
    this.schema.dropTableIfExists('tenants')
  }
}
