// database/migrations/003_auth_access_tokens.ts
// AUTH-03, AUTH-05: auth_access_tokens — generated by @adonisjs/auth v10.
// CRITICAL: tokenable_id is bigInteger (NOT integer) — users.id is bigint serial (D-09).
//   Using table.integer() would silently truncate large user IDs. Always use bigInteger.
// No RLS on this table — tenant isolation enforced via users JOIN.
import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'auth_access_tokens'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.increments('id').unsigned().primary()
      // CRITICAL: bigInteger here — users.id is bigIncrements (bigint)
      table
        .bigInteger('tokenable_id')
        .unsigned()
        .notNullable()
        .references('id')
        .inTable('users')
        .onDelete('CASCADE')
      table.string('type').notNullable()
      table.string('name').nullable()
      table.string('hash').notNullable().unique()
      table.text('abilities').notNullable()
      table.timestamp('created_at').notNullable()
      table.timestamp('updated_at').notNullable()
      table.timestamp('last_used_at').nullable()
      table.timestamp('expires_at').nullable()
    })

    this.schema.raw(`GRANT SELECT, INSERT, UPDATE, DELETE ON auth_access_tokens TO app`)
    this.schema.raw(`GRANT USAGE, SELECT ON SEQUENCE auth_access_tokens_id_seq TO app`)
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
